# CUSTOMER CHURN ANALYSIS

In [1]:
import pandas as pd
import numpy as np

#### Load Dataset

In [3]:
data=pd.read_excel(r"C:\Users\tusha\Downloads\customer_churn.xlsx")
df=pd.DataFrame(data)
df

,Customer_ID,Gender,Senior_Citizen,Partner,Dependents,Tenure_Months,Internet_Service,Contract,Payment_Method,Monthly_Charges,Total_Charges,Churn
0,CUST10001,Male,No,No,No,30,Fiber optic,Two year,Mailed check,121.11,3618.91,No
1,CUST10002,Female,No,No,No,45,Fiber optic,Month-to-month,Electronic check,76.74,3649.23,Yes
2,CUST10003,Male,No,No,Yes,61,No,Month-to-month,Electronic check,70.22,4263.80,No
3,CUST10004,Male,Yes,Yes,No,51,DSL,Month-to-month,Bank transfer,71.51,3862.11,Yes
4,CUST10005,Male,No,No,No,9,Fiber optic,Month-to-month,Electronic check,83.80,729.05,No
...,...,...,...,...,...,...,...,...,...,...,...,...
1245,CUST11246,Female,No,Yes,Yes,25,DSL,Month-to-month,Electronic check,34.82,811.21,No
1246,CUST11247,Female,No,Yes,No,3,No,Month-to-month,Bank transfer,73.66,213.52,No
1247,CUST11248,Female,No,Yes,Yes,3,Fiber optic,One year,Electronic check,94.35,288.82,No
1248,CUST11249,Female,No,Yes,No,28,Fiber optic,Month-to-month,Bank transfer,90.72,2567.06,Yes
1249,CUST11250,Female,No,No,No,23,DSL,Two year,Electronic check,89.36,2092.16,No

#### Data Cleaning

In [5]:
df.head()

,Customer_ID,Gender,Senior_Citizen,Partner,Dependents,Tenure_Months,Internet_Service,Contract,Payment_Method,Monthly_Charges,Total_Charges,Churn
0,CUST10001,Male,No,No,No,30,Fiber optic,Two year,Mailed check,121.11,3618.91,No
1,CUST10002,Female,No,No,No,45,Fiber optic,Month-to-month,Electronic check,76.74,3649.23,Yes
2,CUST10003,Male,No,No,Yes,61,No,Month-to-month,Electronic check,70.22,4263.80,No
3,CUST10004,Male,Yes,Yes,No,51,DSL,Month-to-month,Bank transfer,71.51,3862.11,Yes
4,CUST10005,Male,No,No,No,9,Fiber optic,Month-to-month,Electronic check,83.80,729.05,No

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1250 entries, 0 to 1249
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Customer_ID       1250 non-null   object
 1   Gender            1250 non-null   object
 2   Senior_Citizen    1250 non-null   object
 3   Partner           1250 non-null   object
 4   Dependents        1250 non-null   object
 5   Tenure_Months     1250 non-null   int64
 6   Internet_Service  1250 non-null   object
 7   Contract          1250 non-null   object
 8   Payment_Method    1238 non-null   object
 9   Monthly_Charges   1250 non-null   float64
 10  Total_Charges     1238 non-null   float64
 11  Churn             1250 non-null   object
dtypes: float64(2), int64(1), object(9)
memory usage: 117.3+ KB

In [7]:
df.shape

(1250, 12)

In [8]:
df.columns

Index(['Customer_ID', 'Gender', 'Senior_Citizen', 'Partner', 'Dependents',
       'Tenure_Months', 'Internet_Service', 'Contract', 'Payment_Method',
       'Monthly_Charges', 'Total_Charges', 'Churn'],
      dtype='object')

In [10]:
df.describe()

       Tenure_Months  Monthly_Charges  Total_Charges
count    1250.000000      1250.000000    1238.000000
mean       36.332800        77.261440    2812.807278
std        20.871093        23.185012    1904.636561
min         1.000000        20.000000      38.600000
25%        18.000000        60.680000    1195.600000
50%        37.000000        76.205000    2524.715000
75%        54.000000        93.180000    4126.570000
max        72.000000       137.000000    9269.250000

In [11]:
df.tail()

,Customer_ID,Gender,Senior_Citizen,Partner,Dependents,Tenure_Months,Internet_Service,Contract,Payment_Method,Monthly_Charges,Total_Charges,Churn
1245,CUST11246,Female,No,Yes,Yes,25,DSL,Month-to-month,Electronic check,34.82,811.21,No
1246,CUST11247,Female,No,Yes,No,3,No,Month-to-month,Bank transfer,73.66,213.52,No
1247,CUST11248,Female,No,Yes,Yes,3,Fiber optic,One year,Electronic check,94.35,288.82,No
1248,CUST11249,Female,No,Yes,No,28,Fiber optic,Month-to-month,Bank transfer,90.72,2567.06,Yes
1249,CUST11250,Female,No,No,No,23,DSL,Two year,Electronic check,89.36,2092.16,No

In [12]:
# missing value check
df.isnull().sum()

Customer_ID          0
Gender               0
Senior_Citizen       0
Partner              0
Dependents           0
Tenure_Months        0
Internet_Service     0
Contract             0
Payment_Method      12
Monthly_Charges      0
Total_Charges       12
Churn                0
dtype: int64

In [13]:
# missing value remove
df.dropna()

,Customer_ID,Gender,Senior_Citizen,Partner,Dependents,Tenure_Months,Internet_Service,Contract,Payment_Method,Monthly_Charges,Total_Charges,Churn
0,CUST10001,Male,No,No,No,30,Fiber optic,Two year,Mailed check,121.11,3618.91,No
1,CUST10002,Female,No,No,No,45,Fiber optic,Month-to-month,Electronic check,76.74,3649.23,Yes
2,CUST10003,Male,No,No,Yes,61,No,Month-to-month,Electronic check,70.22,4263.80,No
3,CUST10004,Male,Yes,Yes,No,51,DSL,Month-to-month,Bank transfer,71.51,3862.11,Yes
4,CUST10005,Male,No,No,No,9,Fiber optic,Month-to-month,Electronic check,83.80,729.05,No
...,...,...,...,...,...,...,...,...,...,...,...,...
1245,CUST11246,Female,No,Yes,Yes,25,DSL,Month-to-month,Electronic check,34.82,811.21,No
1246,CUST11247,Female,No,Yes,No,3,No,Month-to-month,Bank transfer,73.66,213.52,No
1247,CUST11248,Female,No,Yes,Yes,3,Fiber optic,One year,Electronic check,94.35,288.82,No
1248,CUST11249,Female,No,Yes,No,28,Fiber optic,Month-to-month,Bank transfer,90.72,2567.06,Yes
1249,CUST11250,Female,No,No,No,23,DSL,Two year,Electronic check,89.36,2092.16,No

In [15]:
# missing value fill
df.fillna

<bound method NDFrame.fillna of      Customer_ID  Gender Senior_Citizen Partner Dependents  Tenure_Months  \
0      CUST10001    Male             No      No         No             30
1      CUST10002  Female             No      No         No             45
2      CUST10003    Male             No      No        Yes             61
3      CUST10004    Male            Yes     Yes         No             51
4      CUST10005    Male             No      No         No              9
...          ...     ...            ...     ...        ...            ...
1245   CUST11246  Female             No     Yes        Yes             25
1246   CUST11247  Female             No     Yes         No              3
1247   CUST11248  Female             No     Yes        Yes              3
1248   CUST11249  Female             No     Yes         No             28
1249   CUST11250  Female             No      No         No             23

     Internet_Service        Contract    Payment_Method  Monthly_Charges  \
0         Fiber optic        Two year      Mailed check           121.11
1         Fiber optic  Month-to-month  Electronic check            76.74
2                  No  Month-to-month  Electronic check            70.22
3                 DSL  Month-to-month     Bank transfer            71.51
4         Fiber optic  Month-to-month  Electronic check            83.80
...               ...             ...               ...              ...
1245              DSL  Month-to-month  Electronic check            34.82
1246               No  Month-to-month     Bank transfer            73.66
1247      Fiber optic        One year  Electronic check            94.35
1248      Fiber optic  Month-to-month     Bank transfer            90.72
1249              DSL        Two year  Electronic check            89.36

      Total_Charges Churn
0           3618.91    No
1           3649.23   Yes
2           4263.80    No
3           3862.11   Yes
4            729.05    No
...             ...   ...
1245         811.21    No
1246         213.52    No
1247         288.82    No
1248        2567.06   Yes
1249        2092.16    No

[1250 rows x 12 columns]>

In [16]:
# duplicated rows check
df.duplicated().sum()

np.int64(0)

In [17]:
# duplicated rows remove
df.drop_duplicates()

,Customer_ID,Gender,Senior_Citizen,Partner,Dependents,Tenure_Months,Internet_Service,Contract,Payment_Method,Monthly_Charges,Total_Charges,Churn
0,CUST10001,Male,No,No,No,30,Fiber optic,Two year,Mailed check,121.11,3618.91,No
1,CUST10002,Female,No,No,No,45,Fiber optic,Month-to-month,Electronic check,76.74,3649.23,Yes
2,CUST10003,Male,No,No,Yes,61,No,Month-to-month,Electronic check,70.22,4263.80,No
3,CUST10004,Male,Yes,Yes,No,51,DSL,Month-to-month,Bank transfer,71.51,3862.11,Yes
4,CUST10005,Male,No,No,No,9,Fiber optic,Month-to-month,Electronic check,83.80,729.05,No
...,...,...,...,...,...,...,...,...,...,...,...,...
1245,CUST11246,Female,No,Yes,Yes,25,DSL,Month-to-month,Electronic check,34.82,811.21,No
1246,CUST11247,Female,No,Yes,No,3,No,Month-to-month,Bank transfer,73.66,213.52,No
1247,CUST11248,Female,No,Yes,Yes,3,Fiber optic,One year,Electronic check,94.35,288.82,No
1248,CUST11249,Female,No,Yes,No,28,Fiber optic,Month-to-month,Bank transfer,90.72,2567.06,Yes
1249,CUST11250,Female,No,No,No,23,DSL,Two year,Electronic check,89.36,2092.16,No

In [18]:
# data types check
df.dtypes

Customer_ID          object
Gender               object
Senior_Citizen       object
Partner              object
Dependents           object
Tenure_Months         int64
Internet_Service     object
Contract             object
Payment_Method       object
Monthly_Charges     float64
Total_Charges       float64
Churn                object
dtype: object